version: '3'
services:
  charana:
    build: .
    image: charana
    ports:
      - 8080:8080
      - 4848:4848
    volumes:
      - ..:/proj
    command: >-
      sh -c "
      asadmin start-domain &&
      asadmin deploy --contextroot charana /proj/charana-war/target/charana-war-*.war &&
      tail -f /glassfish5/glassfish/domains/domain1/logs/server.log"
